### PR TITLE
Add save button to figure window

### PR DESCRIPTION
**Pull request by OhadNir9**
Solves issue #18

### CODE REVIEW

**Comment by OhadNir9** [comment]
Figure window:


Save dialog:

**Review by saroad2 — CHANGES_REQUESTED** [review]
Thank you for your contribution!

Two issues I want to raise:

1. I believe that the save button should be bellow the figure. If you have troubles making that happen, I'll try do it myself.
2. We should support saving the figure in other file types such as JPG for example, not just PNG.

Please let me know if you manage to make those changes.

**Comment by OhadNir9** [comment]
New button location:

**Comment by saroad2** [comment]
This PR requires beeware/toga#1035 in order to fully be tested. Waiting for it to be merged and new toga version before merging this one.

**Review by saroad2 — APPROVED** [review]

**Pull request merged**
